### ISSUE TITLE
Validate Now throws Access Violation

### ISSUE THREAD

**Issue by tgeysen78** [morbac/xmltools#144] opened 2022-03-03 10:51 UTC
XML Tools 3.1.1.12 in notepad++ v8.3.2 64bit displays an 'access violation' popup when trying to validate an xml. there is no XSD defined in the XML itself, only a default namespace

**Comment by morbac** [comment] 2022-03-03 15:24
Can you please provide a sample file to help me reproduce the issue ?

**Comment by mmucha2107** [comment] 2022-03-05 17:32
I confirm the problem. W 11 Pro, Notepad++ v. 8.3.2, XML Tools 3.1.1.12.  The problem did not exist for notepad 8.2.1 and
XML tools 3.1.1.10.  Looks like a technical quirk.
[Access_Violation_example.xml.txt](https://github.com/morbac/xmltools/files/8191122/Access_Violation_example.xml.txt)
This is just one small example, but it is a regular case with all xml files I checked. Due to GDPR I would have anonymize too much data to provide you more cases.

Regards
MM

**Comment by SwiX83** [comment] 2022-03-09 12:56
Same issue here with XML Tools 3.1.1.12 in notepad++ v8.3.2 64bit. The issue does NOT occur with XMLTools 3.1.1.**11** in notepad++ v8.3.2 64bit.

**Comment by DanielPiersonLN** [comment] 2022-03-09 21:04
I'm having the same problem.  Happens with this simplest XML 

<Data>
	<Field1>A</Field1>
	<Field2>A</Field2>
</Data>

The error occurs immediately upon clicking the Validate Now menu option, where, normally, the dialog would pop up to enter the xsd.

**Comment by ChiefGreenSmoke** [comment] 2022-03-14 00:25
how do you downgrade from 3.1.1.12 to 3.1.1.11?
when i go to xml tools in notepadd++it only gives the option to get the newest version?

**Comment by Gitoffthelawn** [comment] 2022-03-14 01:22
@ChiefGreenSmoke You can download older versions from here: https://github.com/morbac/xmltools/releases

**Comment by ChiefGreenSmoke** [comment] 2022-03-14 01:51
thanks i actually did that already but when i go to look for the xml tools in notepad id isn't there. guess im not sure how to link the older version to it

**Comment by morbac** [comment] 2022-03-14 08:05
The fix will be inlcuded in release 3.1.1.13.
For thoses who cannot wait, a pre-release is available here: [XMLTools-Fix144.zip](https://github.com/morbac/xmltools/files/8242863/XMLTools-Fix144.zip)

**Comment by morbac** [comment] 2022-04-02 09:10
[New release 3.1.1.13](https://github.com/morbac/xmltools/releases/tag/3.1.1.13) should fix the issue

**Closed by morbac** 2022-04-02 09:10 UTC
