### ISSUE TITLE
current XML path with predicates gives xml path without predicates

### ISSUE THREAD

**Issue by Ol-li** [morbac/xmltools#139] opened 2022-02-10 15:14 UTC
in the past this feature was ok and the result included the numbers of the tags if there were multiple similar tags. Now this is no longer working. I have xml files like this

```
<x>
	<a>xfh</a>
	<a>cvbb</a>
</x>
```

Cursor at "cvbb" the result is  "/x/a". I was expecting /x/a[2]

**Comment by morbac** [comment] 2022-02-13 08:17
Duplicate of #131

**Closed** 2022-03-22 20:14 UTC
