### ISSUE TITLE
XMLTools generates Plugin Exception in Notepad++ 

### ISSUE THREAD

**Issue by ergins23** [morbac/xmltools#160] opened 2022-04-13 13:42 UTC
Using XMLTools 3.1.1.12, unicode 64 bit with Notepad++ 8.3.3 64 bit.

Reproduction steps.
* Open an XML file (no XSL)
* Make a change
* Save the file

A messagebox is shown
Title:
`Plugin Exception`
Text:
`An exception occurred due to plugin: XMLTools.dll`
`Exception reason: Access violation`

![XMLTools-Exception](https://user-images.githubusercontent.com/5024446/163193535-3db2e0ef-51a7-48d9-926e-97b9759d93f1.png)

If you press OK the file is saved correctly and Notepad++ is still running with no adverse effects.

**Comment by morbac** [comment] 2022-04-13 14:40
Duplicate of #144 and #153
This was fixed in [release 3.1.1.13](https://github.com/morbac/xmltools/releases/tag/3.1.1.13). Pull request has been merged into npp plugins list. So you can either install version 3.1.1.13 manually or wait next NPP release and install it with plugins admin.

**Closed by morbac** 2022-04-13 14:40 UTC

**Comment by ergins23** [comment] 2022-04-13 15:46
Awesome, thanks for the information!
