### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by vinsworldcom** [morbac/xmltools#148] opened 2022-03-14 19:53 UTC
Using latest Notepad++ 8.3 64-bit and XML Tools 3.1.1.12:

create simple XML file:

```XML
<?xml version="1.0"?>
<file>
</file>
```

Plugins => XML Tools => Validate now

Access Violation

![image](https://user-images.githubusercontent.com/9657169/158250162-c44fca85-5f4f-4d2a-8efd-90acf57c2f34.png)

Notepad++ v8.3.2   (64-bit)
Build time : Mar 13 2022 - 01:35:47
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1586
Current ANSI codepage : 1252
Plugins : XMLTools.dll

**Comment by vinsworldcom** [comment] 2022-03-15 19:59
@morbac - this may be related or duplicate of #144 - close if so.

**Comment by morbac** [comment] 2022-03-18 19:13
Duplicate of #144

**Closed by morbac** 2022-03-18 19:13 UTC
