### ISSUE TITLE
Crash when unexpected/faulty XPath notation

### ISSUE THREAD

**Issue by Andrew73174** [morbac/xmltools#123] opened 2021-10-14 08:56 UTC
When trying to evaluate an XPath expression that is faulty npp crashes.
This is the XML file used:
`<notelist>
	<note>
		<to>Jane</to>
		<from>John</from>
		<heading lang="EN">Reminder</heading>
		<body>Don't forget me!</body>
	</note>
	<note>
		<to>John</to>
		<from>Jane</from>
		<heading lang="DE">Antwort</heading>
		<body lang="DE">Danke!</body>
	</note>
	<note>
		<to>Jane</to>
		<from>John</from>
		<body>You are welcome.</body>
	</note>
	<note>
		<to>John</to>
		<from>Jane</from>
		<heading>Reminder</heading>
		<body lang="DE">Bis bald!</body>
	</note>
</notelist>`

XPath querries that fail:
`/descendant-or- self::*` >because of space
`/descendant-or-aself::*` >because of a
`/ /` >because of space
`//*[position(1)=3]` because position should have no arguments
and so on

XML Tools Version 3.1.1.8 (installed via Plugin Manager within NPP)
NPP Version 8.1.6

**Comment by morbac** [comment] 2021-10-14 10:32
In [version 3.1.19](https://github.com/morbac/xmltools/releases/tag/3.1.1.9) I fixed a memory allocation which caused NPP crash when using ANSI encoding.
Could you please test with this version and see if NPP still crashes ?

Btw I not that annotation-style errors is not appropriate for XPath evaluation errors. I'll change that in next release.

**Comment by morbac** [comment] 2021-10-14 14:00
The issue is a duplicate of #96

**Closed as completed** 2021-10-28 06:18 UTC
