### ISSUE TITLE
access violation

### ISSUE THREAD

**Issue by ChiefGreenSmoke** [morbac/xmltools#147] opened 2022-03-13 22:39 UTC
hello i am new to this so i apologize in advance, i keep getting the pluginsmanager::runplugincommand exceptions
 access violation. i have the latest version of notepad++[v8.3.2] and the latest xmltools [3.1.1.12].

**Comment by Gitoffthelawn** [comment] 2022-03-14 01:21
What tasks are you trying to perform when you get those errors?

**Comment by morbac** [comment] 2022-03-14 07:56
Duplicate of #144

**Closed by morbac** 2022-03-14 07:56 UTC
